defaults:
  - _self_
  - train

dataframe_path: C:/Users/tejbh/Desktop/VS CODE/PROJECT/CryptoPredictions/outputs/2023-04-24/17-35-52/backTest_dataset/
strategy_signal: signal1
buy_stop_loss: 0.9
buy_take_profit: 1.1
sell_stop_loss: 1.1
sell_take_profit: 0.9
