window_size: 10 #5
train_start_date: 2018-09-01 00:00:00
train_end_date: 2024-01-01 00:00:00
valid_start_date: 2024-01-02 00:00:00
valid_end_date: 2025-01-01 00:00:00
features: Date, open, High, Low, close, volume #make sure to have Date High Low
indicators_names: rsi macd


#short_wma, wma, long_wma, ewma, tema, macd, stoch1, stoch2, wpr, rsi_experts, rsi, srsi, bolinger